language: go
go:
  - "1.x"

env: GO111MODULE=on CGO_ENABLED=0

install:
  - go mod download

script:
  - go build ./cmd/gomodproxy
  - go test -v ./...

after_success:
  - mkdir gomods
  - printf 'FROM scratch\nADD gomodproxy /\nADD gomods /\nCMD ["/gomodproxy"]' > Dockerfile
  - docker build -t "sixtlabs/gomodproxy-slim:latest" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "sixtlabs/gomodproxy-slim:latest"
  - if [ ! -z $TRAVIS_TAG ] ; then
      TAG=$(echo $TRAVIS_TAG | sed 's/^v//');
      docker tag sixtlabs/gomodproxy-slim:latest sixtlabs/gomodproxy-slim:$TAG;
      docker push sixtlabs/gomodproxy-slim:$TAG;
    fi
  - printf 'FROM golang\nADD gomodproxy /\nADD gomods /\nCMD ["/gomodproxy"]' > Dockerfile
  - docker build -t "sixtlabs/gomodproxy:latest" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "sixtlabs/gomodproxy:latest"
  - if [ ! -z $TRAVIS_TAG ] ; then
      TAG=$(echo $TRAVIS_TAG | sed 's/^v//');
      docker tag sixtlabs/gomodproxy:latest sixtlabs/gomodproxy:$TAG;
      docker push sixtlabs/gomodproxy:$TAG;
    fi
